### ISSUE TITLE
Doesn't work on Ubuntu

### ISSUE THREAD

**Issue by bu4ak** [nowtilous/Project-Color#11]
| OS   |      PhpStorm      |  Plugin version |
|:----------:|:-------------:|:------:|
|Ubuntu 22.04 jammy|  Build #PS-221.5921.28, built on June 22, 2022 | 1.2.0 |

The color does not change

![image](https://user-images.githubusercontent.com/17143820/178214539-5354acc9-f5ae-44a5-83ce-13f0a4cf413b.png)

**Comment by nowtilous** [comment]
Yea Ubuntu is not supported yet, I'll add support soon

**Comment by nowtilous** [comment]
Release 1.3.0 now supports Linux! enjoy!
