### ISSUE TITLE
Plugin doesn't change any colors

### ISSUE THREAD

**Issue by shaunek** [nowtilous/Project-Color#2]
I tried to install the Intellij-Project-Color plugin in IntelliJ 2021.3.1 and 2021.3.3 and it did not work. I downloaded the 1.0.0 release (zip file) and used IntelliJ's install plugin from disk option. The color chooser pops up just fine and I can select a color, however, when I click OK to close out the color picker dialog nothing changes. The title bar doesn't change colors.

Here is all my version information from the About dialog, let me know if there is anything else I can do to help resolve this. I've been wanting a plugin like this for a while!

```
IntelliJ IDEA 2021.3.3 (Community Edition)
Build #IC-213.7172.25, built on March 15, 2022
Runtime version: 11.0.14.1+1-b1751.46 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    monokai-pro (1.8.1)
    idea.plugin.protoeditor (213.6461.28)
    com.thvardhan.gradianto (4.5)
    com.samdark.intellij-visual-studio-code-dark-plus (2.5)
    com.markskelton.one-dark-theme (5.6.0)
    com.jetbrains.edu (2022.5-2021.3-994)
    com.jetbrains.darkPurpleTheme (1.3)
    com.intellij.plugins.watcher (213.6461.19)
    org.jetbrains.kotlin (213-1.7.0-release-281-IJ6777.52)
    com.github.nowtilous.intellijprojectcolor (1.0.0)
    com.github.menwhorust.tomorrownighttheme (0.0.16)
    com.4lex4.intellij.solarized (2.4.0)
    Key Promoter X (2021.3)
    Docker (213.7172.6)
    org.intellij.scala (2021.3.22)

Kotlin: 213-1.7.0-release-281-IJ6777.52
```
Wondering if it could have something to do with the fact that I am on MacOS and not Windows

**Comment by nowtilous** [comment]
hey, thanks for letting me know! I'm working on a new version with some new features and bugfixes right now,
i'll let you know when this is resolved:)

**Comment by nowtilous** [comment]
Hey, I just released version 1.2 which supports MacOS! have fun

**Comment by MadeleineSmith** [comment]
Epic, thank you 💯

**Comment by shaunek** [comment]
Confirming that 1.2 worked on my macos machine. Was great that I was able to search/install from within Intellij's plugin screen. Many thanks for this!
