### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by jonascc** [nowtilous/Project-Color#21]
Hello,

First of all, that's a great project, very useful :slightly_smiling_face:.

I noticed it doesn't have a licence, though (maybe an oversight?), which makes it not truly open source. If you'd like to accept contributions from the community, I would suggest you to add a licence. Here are some link that may help:

[Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

[Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

[Choose an open source license](https://choosealicense.com/)

[Open Source Guides](https://opensource.guide/)

**Comment by nowtilous** [comment]
donesies
