### ISSUE TITLE
Sup Yon! I cant get it working.

### ISSUE THREAD

**Issue by b-hayes** [nowtilous/Project-Color#6]
Im guessing the settings for it should be here?
<img width="885" alt="image" src="https://user-images.githubusercontent.com/30540495/177471973-4b68f272-7acd-466d-8c03-d8f29bbc4776.png">
THis settings page fails to load.

If not please let me know if I am in the wong location.

PHPSTORM 2022.1.3, macos 12.4.
Im using M1 macbook if that complicates things at all.

**Comment by nowtilous** [comment]
Hey, 
As shown in the screenshots section on the  README, there should be a colorful cube button in your navigation bar when you open a project, next to the build/debug/execute buttons.

**Comment by b-hayes** [comment]
Ah of course, should probably add that to the plugin description.
Looks like its working 🥳
<img width="310" alt="image" src="https://user-images.githubusercontent.com/30540495/177515519-5384668f-f61c-4aef-9eea-fa50b0958c8f.png">
Thanks Yon!
