### ISSUE TITLE
Foreground color bug

### ISSUE THREAD

**Issue by krasa** [nowtilous/Project-Color#7]
It happens when changing ` View | Appearance` but also sometimes randomly.  It should stay black to get a good contrast.
![image](https://user-images.githubusercontent.com/1160875/177490439-57798d5b-8efe-49f2-a0df-04dfc0bc9983.png)

![image](https://user-images.githubusercontent.com/1160875/177490347-ef3877e5-adef-4fd6-be5c-e6a1cab45a70.png)

```
IU-222.3244.4
```

**Comment by nowtilous** [comment]
I'll release a patch soon, thanks!

**Comment by nowtilous** [comment]
Released a patched version, 1.2.1, please try it and update me if the problem still occurs.
Also, jetbrains will take a few days to approve the update, but you can download the version from the release page.

**Comment by nowtilous** [comment]
The patch got approved, you can download 1.2.1 through the plugin manager
